services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=rika_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
